name: Compile server on merge
on:
  push:
    branches:
      - main
    paths: ["server/**"]
jobs:
  build_server:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Create .env file for server
      # Source: https://stackoverflow.com/a/63350136
      - run: "(cd server
      && touch .env
      && echo CONNECTION_URL_TEST=${{ secrets.CONNECTION_URL_TEST }} >> .env
      && cat .env
      )"
      - run: (cd server && npm ci)
      - run: (cd server && npm run build)
      - run: (cd server && npm run test)
